file(READ "${CMAKE_CURRENT_LIST_DIR}/../version.txt" VERSION_STR)
string(STRIP "${VERSION_STR}" VERSION_STR)

string(REPLACE "." ";" VERSION_PARTS "${VERSION_STR}")
list(GET VERSION_PARTS 0 VERSION_MAJOR)
list(GET VERSION_PARTS 1 VERSION_MINOR)
list(GET VERSION_PARTS 2 VERSION_PATCH)
list(LENGTH VERSION_PARTS PARTS_COUNT)
if(PARTS_COUNT GREATER 3)
    list(GET VERSION_PARTS 3 VERSION_REVISION)
else()
    set(VERSION_REVISION 0)
endif()

message(STATUS "Version: ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_REVISION}")


set(LUNA_VERSION "{${VERSION_MAJOR},${VERSION_MINOR},${VERSION_PATCH},${VERSION_REVISION}}")
add_library(VERSION_DEF ${CMAKE_CURRENT_LIST_DIR}/version_def.cpp)
target_compile_definitions(VERSION_DEF PRIVATE
    LUNA_VERSION_=${LUNA_VERSION})
include(${CMAKE_CURRENT_LIST_DIR}/version/generate_product_version.cmake)

generate_product_version(
	versioninfo
   NAME "LunaTranslator"
   COMPANY_COPYRIGHT "Copyright (C) 2026 HIllya51"
   ICON ${PATH_TO_APPLICATION_ICON}
   VERSION_MAJOR ${VERSION_MAJOR}
   VERSION_MINOR ${VERSION_MINOR}
   VERSION_PATCH ${VERSION_PATCH}
   VERSION_REVISION ${VERSION_REVISION}
   COMPANY_NAME "HIllya51"
)