name: _

on:
  workflow_call:
    # inputs: 
    #   createrelease:
    #     type: boolean
    #     default: false
    #     required: false 
jobs:
  buildall:
    runs-on: windows-latest
    strategy:
      matrix:
        include:  
          - arch: x86
            target: winxp
          - arch: x86
            target: win7
            pythonversion: '3.7.9' 
          - arch: x64
            target: win7
            pythonversion: '3.7.9' 
          - arch: x64
            target: win10
            pythonversion: '3.13.13'  
    steps:
      - uses: actions/checkout@v6
      # - uses: microsoft/setup-msbuild@v2
      - if: matrix.target == 'winxp'
        run: |
            Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
            $InstallPath = "C:\Program Files\Microsoft Visual Studio\18\Enterprise"
            $componentsToAdd = @(
              "Microsoft.VisualStudio.Component.WinXP"
            )
            [string]$workloadArgs = $componentsToAdd | ForEach-Object {" --add " +  $_}
            $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
            $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
            if ($process.ExitCode -eq 0)
            {
                Write-Host "components have been successfully added"
                Get-ChildItem C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.Windows.XPSupport.*
            }
            else
            {
                Write-Host "components were not installed"
                exit 1
            }
      # - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
      #   with:
      #     sdk-version: 26100
      - if: matrix.target != 'winxp'
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.pythonversion }}
          architecture: ${{ matrix.arch }}
      - if: matrix.target != 'win10'
        uses: actions/setup-python@v6
        with:
          python-version: 3.13.13
          architecture: x64
      - run: C:\hostedtoolcache\windows\Python\3.13.13\x64\python src/scripts/build_lunatranslator.py cpp ${{ matrix.arch }} ${{ matrix.target }}
      - run: C:\hostedtoolcache\windows\Python\3.13.13\x64\python src/scripts/build_lunatranslator.py hook ${{ matrix.arch }} ${{ matrix.target }}
      - if: matrix.target != 'winxp'
        run:  C:\hostedtoolcache\windows\Python\3.13.13\x64\python src/scripts/build_lunatranslator.py pyrt ${{ matrix.arch }} ${{ matrix.pythonversion }} ${{ matrix.target }}
      - run:  C:\hostedtoolcache\windows\Python\3.13.13\x64\python src/scripts/build_lunatranslator.py merge ${{ matrix.arch }} ${{ matrix.target }}

      - uses: actions/upload-artifact@v7
        with:
          name: LunaTranslator_${{ matrix.arch }}${{ matrix.target != 'win10' && format('_{0}', matrix.target) || '' }}
          path: src/build/LunaTranslator_${{ matrix.arch }}${{ matrix.target != 'win10' && format('_{0}', matrix.target) || '' }}

      # - uses: actions/attest-build-provenance@v2.2.0
      #   with:
      #       subject-path: src/build/LunaTranslator_${{ matrix.arch }}_${{ matrix.target }}
