name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
       - run: |
          curl --request GET \
          --url https://lunatranslator.org/githubupdatenotify \
          --header 'authorization: ${{ secrets.GITHUB_TOKEN }}'\
          --header 'repository: ${{ github.repository }}'